# Generated by Django 5.1 on 2026-02-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_fundraiser_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
